### PR TITLE
Glibc 2.21 upstream stable branch fixes and gcc 4.9.3

### PR DESCRIPTION
**Pull request by moths**

### CODE REVIEW

**Comment by kimrhh** [comment]
wouldn't it be better to upgrade to glibc-2.22 while we are at it? instead of adding all the patches :)

**Comment by esben** [comment]
No, not for 5.0.  GCC and glibc upgrade is 6.0 stuff.

**Comment by moths** [comment]
Staying on 2.21 for 5.0.0 release seems the right thing to do. The patches are not 2.21 to 2.22, but 2.21 stable branch fixes.

**Comment by kimrhh** [comment]
@esben eh, this PR is upgrading GCC ;) but if you consider 2.22 a more unstable upgrade then fine, sounds like it is based on mortens input

**Comment by esben** [comment]
gcc 4.9.3 is a bugfix release, glibc 2.22 is a normal release, so I agree with @moths

**Comment by kimrhh** [comment]
try synchronizing this, now that kexec-tools should be fixed (hat tip @sknsean )

**Comment by esben** [comment]
I'll merge it now, but I think we should drop gcc 4.9.2 before release of OE-lite/core 5.0.0.

**Pull request merged**
