### PR TITLE
64bit sdk fix, kernel newer than 4.0 fix, arch.py cleanup

### PR DESCRIPTION
**Pull request by sknsean**
Some fixes and some cleanup

### CODE REVIEW

**Comment by esben** [comment]
Ok, so any 2.6 kernels and older, and any 3.x kernels older than 3.7.
So if the header layout change went in at 3.7, it should be perfect :)

**Comment by sknsean** [comment]
I haven't checked if the header change was in 3.7 but I guess the original author have done this ;-)

**Comment by sknsean** [comment]
Should I remove the glibc 64bit sdk fix from this pull request?

**Comment by esben** [comment]
Yes, if you remove that, we can merge the other two now. But please repost the 64 bit sdk fix in another PR. We clearly want it merged :)

**Pull request merged**
