### PR TITLE
glibc 2.22

### PR DESCRIPTION
**Pull request by sknsean**
Maybe for milestone 6.0.0

### CODE REVIEW

**Comment by esben** [comment]
LGTM, but waiting for jenkins to give green light :)

**Comment by esben** [comment]
You should probably apply the following patch to valgrind:
https://github.com/envytools/valgrind/commit/243de7f3e62e2d22fae1be08b5e28d5afef5f040

**Comment by sknsean** [comment]
Do I need to include all the patches from https://sourceware.org/git/?p=glibc.git;a=shortlog;h=refs/heads/release/2.22/master in this PR?

**Comment by esben** [comment]
Maybe.  But in that case, please don't convert the git commit log to a patch series.  Switch to git fetcher, and fetch the proper commit.  And keep it in separate commit, so we can play with revert on it in case of problems.

**Comment by sknsean** [comment]
Glibc 2.23 have been released :-)
@esben do you want 2.22 or 2.23 for 6.0.0?

**Comment by esben** [comment]
AFAIK, 2.23 is not released yet.  Until then, head of 2.22 release branch should be used.  Upgrading to 2.23 as soon as it is released.

**Comment by esben** [comment]
LGTM

**Pull request merged**
