### PR TITLE
add cpu arch imx7

### PR DESCRIPTION
**Pull request by sknsean**

### CODE REVIEW

**Comment by esben** [comment]
Did you want this in 6.0.0 or 7.0.0?

**Comment by sknsean** [comment]
don't care :-)

**Comment by esben** [comment]
Ok, I'll try and ask in a different way.  How much testing have been done with the current master branch on i.MX7 ?

**Comment by sknsean** [comment]
It have been tested as much, as we have a running PIL distro for an imx7sabresd.
Our PIL distro is currently based on release 5.0

**Pull request merged**
