### PR TITLE
gcc6

### PR DESCRIPTION
**Pull request by sknsean**

### CODE REVIEW

**Comment by sknsean** [comment]
This depends on #107

**Comment by esben** [comment]
@sknsean can you rebase this?

**Comment by sknsean** [comment]
This depends on oe-lite/base#375 oe-lite/base#376 oe-lite/base#377 oe-lite/base#379 oe-lite/base#380

**Comment by esben** [comment]
Ok, so we will rebuild this when those 5 PR's have been merged.

**Comment by sknsean** [comment]
also depends on https://github.com/oe-lite/base/pull/386

**Comment by sknsean** [comment]
and https://github.com/oe-lite/base/pull/387

**Comment by sknsean** [comment]
and finally https://github.com/oe-lite/base/pull/391 (if the buildbot is correct)

**Pull request merged**
