### PR TITLE
linux-headers: version bump to 4.4.23

### PR DESCRIPTION
**Pull request by sknsean**
Bump linux-headers to newest LTS

### CODE REVIEW

**Comment by sknsean** [comment]
Depends on https://github.com/oe-lite/base/pull/394

**Comment by kimrhh** [comment]
are we just going to let anyone downstream with kernels <=4.4 "keep the pieces" or could we add a big fat warning if they are ending up with a combination that is not good?

any real reason to delete the old headers?

**Comment by esben** [comment]
How does this depend on oe-lite/base#394 (socat upgrade)?

**Comment by sknsean** [comment]
Can't remeber :-)

**Pull request merged**
