### PR TITLE
Updated GCC to 4.8.5

### PR DESCRIPTION
**Pull request by sknsean**
The 2x svn patches and the pr- patch is already applied in 4.8.5

### CODE REVIEW

**Comment by esben** [comment]
Were you able to verify that the 3 dropped patches are not needed anymore?

**Comment by sknsean** [comment]
Opened the files and verified the patches where already applied...

**Comment by esben** [comment]
Sounds good.

**Comment by sknsean** [comment]
Just double checked. They are not applied. :-) But the on the builds i have done and the CI showed no errors.
I'll look into it later

**Comment by sknsean** [comment]
I accidently unpacked 4.8.2 :-) They are definitely applied.

**Comment by esben** [comment]
Sounds good :)

**Comment by mikaelj** [comment]
..and this version is the one that doesn't murder my Linux kernel? :)

-Micke
Den 10 okt 2015 17:23 skrev "Esben Haabendal" <notifications@github.com>:

**Comment by sknsean** [comment]
I hope so :-) I can compile a 3.18 lts kernel now

**Comment by esben** [comment]
And this should therefore also close issues #38 and #42

**Pull request merged**
